<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVvT6koE\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVvT6koE/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVvT6koE.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVvT6koE\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVvT6koE\App_KernelDevDebugContainer([
    'container.build_hash' => 'VvT6koE',
    'container.build_id' => 'eec2ebda',
    'container.build_time' => 1694313466,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVvT6koE');
